### ISSUE TITLE
First!

### ISSUE THREAD

**Issue by konijn** [ex/utils#1]
Greetings,

I found 2 fairly common keywords missing in hx.stx:

```
override
null
```

Other than that, thank you for taking the time to build hx.stx and share it.

**Comment by konijn** [comment]
Minor note: I actually moved null to KEYWORD=Built-in objects and override to #KEYWORD=Reserved words

**Comment by konijn** [comment]
Pull request:
https://github.com/ex/utils/pull/2

**Comment by ex** [comment]
Thank you!
